# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmergencyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmergencyApp
  pod 'Firebase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseMessaging'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod ‘AlamofireObjectMapper’
  pod ‘Alamofire’, ‘4.5.1’
end
